Tonkel/take-me-out

assets/css/style.css
adds margin around map and reduces height a bit
Fixes #[issue]
fixes map height and margin
path/to/file
- changed css
- change
- change
=> adds margin around map and reduces height a bit

index.html
Links the files to the header
Fixes #[issue]
Clicking on home will bring you to index.html file
clicking on the About Us will bring you to aboutus.html
clicking on FAQ will take you to faq.html
changed the href attribute for each of these items
Try clicking on the nav bar links
=> adds links to header nav bar

aboutus.html, faq.html
Adds header for each nav bar page
Fixes #[issue]
Creates a cohesive look for the site along all pages
adds in the header html to the faq.html and aboutus.html
Navigate to these pages through the nav bar to see the changes displayed
=> adds header to all linked pages

index.html
Fixes #[issue]
path/to/file
- change
- change
- change
=> changed the font t

index.html
Fixes #[issue]
fixes drodown name accuracy
path/to/file
index.html
- change
- change
=> adds acuurate names and choices to the dropdown menus

assets/css/style.css, index.html
Fixes #[issue]
Please provide a detailed explanation of the PR. What existing problem does it solve?  i changed the font size to make more readerable 
path/to/file
- change
- change
- change
=> changed the styling

index.html
Fixes #[issue]
Please provide a detailed explanation of the PR. What existing problem does it solve? 
no issues were found we had to change the file from document to the main title take me out. 
path/to/file
- change
- change
- change
=> changed the title of the page

aboutus.html, faq.html
I made the app uniform and all the tiles have the same font and size
Fixes #[issue]
path/to/file
- change
- change
- change
=> changed the font style of the faq and about us page

assets/js/script.js
Links in the weather API and console logs the weather at your current location
Fixes #[issue]
Adds beginning of weather element 
adds in a getWeather function to retrieve the current weather at your location 
load the page and open the console log to see the logged weather
=> 59 link weather api

assets/js/script.js
the Marker will return business name
parameter in createrMarker function
=> click the marker and it will return the business name

index.html
Fixes #[issue]
path/to/file
- change
- change
- change
=> adds change in html id

index.html
Adds physical weather card to the html
Fixes #[issue]
creates place for weather to be logged
Adds weather card using a css framework that is also linked in the head element
path/to/file
should be visible on the page
=> adds weather card structure

assets/css/style.css
Fixes #[issue]
path/to/file
- change
- change
- change
=> adds modify css stlye sheet for gome and other content

assets/js/script.js, index.html
Adds current weather card to the weather card
Fixes #[issue]
Allows user to see current weather conditions (sunny rainy etc)
adds in src attribute with variable to pull current icon
will show once you load location
=> adds icon display for current weather to the weather card

assets/js/script.js, index.html
Fixes #[issue]
Search Input will log when search button is clicked
=> 79 make the search input save into a variable when the search button is clicked

assets/css/style.css, index.html
Puts the weather next to the map
Fixes #[issue]
Easier user experience
css styling
view on page load
=> puts weather card next to map and ups the size of the weather icon

assets/js/script.js, index.html
Adds the selected radius as the header menu on radius dropdown
Fixes #[issue]
better user interface to see which they've selected
adds javascript function to add event listeners to each radius button and log the selected one
select the radius options to see it in action
=> adds radius selection to menu hader

aboutus.html, assets/css/style.css, faq.html, index.html
changed the background color to blue. 
Fixes #[issue]
background color was changed 
path/to/file
- change
- change
- change
=> 87 changed the background

README.md
created read me template 
Fixes #[issue]
path/to/file
- change
- change
- change
=> 89 create read me template

assets/css/style.css, faq.html
Fixes #[issue]
path/to/file
- change
- change
- change
=> 91 create faq page

assets/css/style.css, index.html
Adds footer
Fixes #[issue]
More cohesive look for the page
Adds footer in html as well as a little styling in css for the footer section
Will show on page load
=> adds footer and a little css styling

assets/js/script.js
Fixes #[issue]
path/to/file
- change
- change
- change
=> adds back map location services

assets/css/style.css, index.html
Fixes #[issue]
path/to/file
- change
- change
- change
=> adds the change in weather color

assets/js/script.js
creates new function to reload map based on radii and search inputs
javascript 
path/to/file
- change
- change
- change
=> 94 search radius functionality

assets/css/style.css
Fixes #[issue]
path/to/file
- change
- change
- change
=> adds color to weather

assets/css/style.css
add back in the footer styling
Fixes #[issue]
css footer styling
On page load
=> adds back footer css that was overwritten

aboutus.html, assets/css/style.css
Fixes #[issue]
path/to/file
- change
- change
- change
=> 100 complete about us page

assets/css/style.css, index.html
style navbar, input area, and search button
CSS style
=> 112 style the navbar search button and input areas

index.html
Fixes #[issue]
path/to/file
- change
- change
- change
=> changes placeholder

index.html
replaces incorrect text
replaces a few words and makes phrase a h3 element
path/to/file
- change
- change
- change
=> replaces some text and makes it larger for visibility

aboutus.html, faq.html
To match the navbar elements in aboutus and faq page to the index page
path/to/file
- change
- change
- change
=> 123 style all navbar so they look the same in all three pages

assets/js/script.js, index.html
Adds list below search bar
Fixes #[issue]
increases functionality by showing the items available
Javascript code 
Loads on page load
=> adds list on page load of items displayed

assets/css/style.css
Fixes #[issue]
path/to/file
- change
- change
- change
=> fixes search button, styles header and footer

assets/css/style.css, assets/js/script.js
Adds Styling for the list of results
Fixes #[issue]
css for the items shown below search bar
Displays once location is shared
=> adds styling to list items

assets/js/script.js
New api key to stay free
Fixes #[issue]
path/to/file
- change
- change
- change
=> new api key

assets/js/script.js
reloads place list whenever a search is made
Fixes #[issue]
Allows only relevant searches to be populated under the search bar
Javascript
USe search function
=> updates place list on search

assets/js/script.js
Allows the buttons in the list to give you directions on the map
Fixes #[issue]
Better user experience
Same ID applied to all buttons and broader scope for the directions function
Click the button in the list
=> adds functionality to the list buttons for directions

aboutus.html, assets/css/style.css, faq.html, index.html
Fixes #[issue]
path/to/file
- change
- change
- change
=> 142 add footer to the other html pages

assets/css/style.css
Styles buttons in list
Fixes #[issue]
Adds a more cohesive look to the page
Css changes
View on load
=> 147 make buttons in list prettier

index.html
fixes map issue with api key
Fixes #[issue]
path/to/file
- change
- change
- change
=> fixes api key

assets/css/style.css
Fixes #[issue]
path/to/file
- change
- change
- change
=> add the css weather color

assets/js/script.js, index.html
Fixes #[issue]
The Search Function now can define by keywords, instead of type of places.
Autocomplete in the input area.
path/to/file
1. type in the search Input and it will give you a list that matches your keyword.
2. Also it will now search based on keywords or the exact address/business/location names.
3. address are harder to use because of the address format
=> 158 optimize the search function and autocomplete from the input
